# Generated by Django 3.0.9 on 2020-09-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(null=True)),
                ('name', models.TextField()),
                ('path', models.TextField()),
                ('endpoint', models.TextField()),
                ('template_name', models.TextField()),
            ],
        ),
    ]
