# Generated by Django 3.0.9 on 2020-09-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='endpoint',
            field=models.TextField(blank=True),
        ),
    ]
