# Generated by Django 3.0.9 on 2020-08-24 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Example: 'flatpages/default.html'", max_length=100, verbose_name='name')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation date')),
                ('last_changed', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last changed')),
                ('published', models.BooleanField(default=False, null=True)),
            ],
            options={
                'verbose_name': 'template',
                'verbose_name_plural': 'templates',
                'db_table': 'custom_dbtemplate',
                'ordering': ('name',),
            },
        ),
    ]
